### ISSUE TITLE
Sugerencias de estilo y typo

### ISSUE THREAD

**Issue by qbreis** [isfegu/blog#7]
**Sugerencias de estilo y typo**

- Referente a como muestras el código en tu blog, se me ocurre que podrías hacer que el c&oacute;digo se mostrase en todo el ancho de la pantalla, si quieres puedes probar a añadir estos estilos en tus etiquetas &lt;pre> que incluyen el contenido &lt;code>:

```width: 100vw;
position: relative;
left: 50%;
right: 50%;
margin-left: -50vw;
margin-right: -50vw;
border-radius: 0;
```

- Referente a la tipografía que usas en el código, veo que has elegido la _Ubuntu Mono_, de la [Dalton Maag](https://www.daltonmaag.com/), fundada por el suizo Bruno Maag en 1991 ;-) Me gusta mucho.<br /><br />Yo reciéntemente he descubierto la [JetBrains Mono](https://www.jetbrains.com/lp/mono/), _a typeface for developers_, de los rusos Philipp Nurullin, diseñador y Konstantin Bulenkov, project manager de JetBrains. Yo me quedo con esta última :-P
<br />- [fonts.google.com/specimen/JetBrains+Mono](https://fonts.google.com/specimen/JetBrains+Mono)<br />- [github.com/JetBrains/JetBrainsMono](https://github.com/JetBrains/JetBrainsMono)

Por si te puede servir.

Disculpa mis faltas de Markdown, si las hay.

**Comment by isfegu** [comment]
@qbreis pues lo he probado y no me acaba de convencer. Cuando hay mucho código seguido, tiene mucha presencia y se come el texto que hay antes y después.

Ni idea de Dalton Maag y que había sido el creador de Ubuntu Mono. En este caso me quedo con ésta, es más "linuxera" :)
